### ISSUE TITLE
Planes removed before the end of transition between pages

### ISSUE THREAD

**Issue by renaudcollet** [martinlaxenaire/vue-curtains#1]
Hi Martin,

Thank you for this awesome library and ported to vue,

I have troubles using it to transition between pages in vue/nuxt because the planes are removed before the end of the transition.
I would like to update the shader according to the transition

Here is the test case :
https://codesandbox.io/p/devbox/nuxt3-vue-curtains-transition-between-pages-jh9ky5
Click on the link on the top to test transitions

**Comment by martinlaxenaire** [comment]
Hi @renaudcollet,

it looks more like a Vue/Nuxt issue to me where the components are unmounted before the page transition ends (you can debug that using the `onBeforeUnmount` hook).
I guess you should look for a way to keep them in the DOM/component tree until the page transition finishes.

Cheers,

**Comment by renaudcollet** [comment]
Thank you for your quick reply,

You are right, it is vue/nuxt triggering onUnmounted hook at the beginning of the transition. 
Vue considers the component is removed from Virtual DOM, so it calls onUnmounted. But the element is still in the DOM.
I will have to modify your Plane.vue to use MutationObserver api to listen for element removed from DOM instead of vue unmounted hook.

I'll close this issue :)

Best,

**Comment by martinlaxenaire** [comment]
Have you tried to use Vue builtin transitions: https://vuejs.org/guide/built-ins/transition#javascript-hooks ?
Haven't tried really but that might be a way to delay the component unmounting while updating your uniforms.

**Comment by renaudcollet** [comment]
Yes I do use vue transitions hook, you can see in the test case I made, see in folder transitions/page-transitions.js
https://codesandbox.io/p/devbox/nuxt3-vue-curtains-transition-between-pages-jh9ky5

The trouble comes from Planes.vue using onUnmounted to remove the plane, this hook is called by vuejs at the beginning of the transition. 

It is weird behavior imo, but it was thought like this in vue2 and still the same in vue3.
See issue here : https://github.com/vuejs/composition-api/issues/443
That links to comment from Evan You here : https://github.com/vuejs/vue/issues/6983#issuecomment-341108090
